### ISSUE TITLE
Upgrade to AWS SDK for Javascript v3

### ISSUE THREAD

**Issue by chiptoma** [nearform/fastify-secrets-aws#367]
Hi there,

Thanks for your work on this plugin.

Would you be able to upgrade the sdk to AWS SDK for Javascript v3?

I believe this is being deprecated.

```
(node:49558) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

**Comment by fedefrusc** [comment]
Hello @simoneb! I open a [PR](https://github.com/nearform/fastify-secrets-aws/pull/381) to fix this issue
